# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3484c3e9425b43a44d5043356a1eb7b7984c94fa7a1dd315bc9f712f2eae991e06056a2dedc6b5371b5f92f5c138f1004a5dba844d22f87f6b90ed04cb6c1882

test:
  secret_key_base: ee707926b91bb8beca387b045f746a74ea34d44d57744a39a0281fd3281e9eb5cb613bd5ffbf700ed85677a78cc0e3ac75c478fc216fbe779a98f26ce17a73ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
